name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Set up Redis 4
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 4

      - name: Cache gem dependencies
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-bundler-

      - name: Install dependencies
        run: |
          bundle config set --local path "vendor/bundle"
          gem install bundler --no-document && bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bin/test
